apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    app: my-app
data:
  LAB_PASSWORD: UzR2aWxsMw==
stringData:
  LAB_USER: sysop
  LAB_BASTION_IP: 172.16.0.1
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  volumes:
  - name: my-secret
    secret:
      secretName: my-secret
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sleep", "infinity"]
    volumeMounts:
    - name: my-secret
      mountPath: /srv/app-config
