apiVersion: batch/v1
kind: Job
metadata:
  name: my-bad-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: my-job
        command: ["/bin/sh", "-c", "xxx"]
      restartPolicy: Never
  completions: 3
  parallelism: 3
  backoffLimit: 2
