apiVersion: v1
kind: Pod
metadata:
  name: nginx-custom
spec:
  volumes:
  - name: nginx-default-conf
    configMap:
      name: nginx-default-conf
  containers:
  - image: nginx
    name: nginx-custom
    volumeMounts:
    - name: nginx-default-conf
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf 
    ports:
    - containerPort: 8080
  restartPolicy: Never
