apiVersion: v1
kind: Pod
metadata:
  name: pod-guaranteed
spec:
  containers:
  - image: busybox
    name: pod-guaranteed
    command: ["/bin/sleep", "infinity"]
    resources:
      requests:
        memory: 192Mi
        cpu: 0.1
      limits:
        memory: 192Mi
        cpu: 0.1
