apiVersion: v1
kind: Namespace
metadata:
  name: testverse
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: testverse
  name: austerity
spec:
  hard:
    pods: "3"
    requests.cpu: "1"
    requests.memory: 1024Mi
    limits.cpu: "2"
    limits.memory: 1536Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: testverse
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: "0.1"
            memory: 96Mi
          limits:
            cpu: "0.2"
            memory: 160Mi
