apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  shareProcessNamespace: true
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/tail", "-f", "/dev/null"]
  - name: alpine
    image: alpine
    command: ["/usr/bin/tail", "-f", "/dev/null"]
